title: orca.pet
description: Socram's website
url: https://orca.pet
repository: socram8888/orca.pet
author: Marcos Del Sol Vives
twitter:
    username: Socramite

theme: jekyll-theme-cayman
timezone: Europe/Madrid
lang: en_US

plugins:
  - jekyll-default-layout
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-render-order
  - jekyll-sitemap
  - jekyll-titles-from-headings

exclude:
  - /commit.bat
  - /commit.sh
  - /devserver.bat
  - /devserver.sh
  - /Gemfile
  - /Gemfile.lock
  - /README.md
