title: orca.pet
description: Socram's website
url: https://orca.pet
repository: socram8888/orca.pet
author: Marcos Del Sol Vives
lang: en_US
twitter:
    username: Socramite

theme: jekyll-theme-cayman

assets:
    caching:
        type: 'memory'

plugins:
  - jekyll-default-layout
  - jekyll-last-modified-at
  - jekyll-optional-front-matter
  - jekyll-relative-links
  - jekyll-sitemap
  - jekyll-titles-from-headings

exclude:
  - /commit.bat
  - /commit.sh
  - /devserver.bat
  - /devserver.sh
  - /Gemfile
  - /Gemfile.lock
  - /README.md
