name: Website CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout source
            uses: actions/checkout@v2
            with:
                # Clone all history so timestamps are accurate
                fetch-depth: 0

          - name: Checkout built
            uses: actions/checkout@v2
            with:
                path: gh-pages
                ref: gh-pages

          - run: ls -laR gh-pages
            name: List all this stuff
            
          - name: Setup cache
            uses: actions/cache@v1
            with:
                path: vendor/bundle
                key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-gems-

          - name: Set up Ruby
            uses: ruby/setup-ruby@v1.32.1
            with:
                ruby-version: 2.5

          - name: Install Ruby dependencies
            run: |
                bundle config path vendor/bundle
                bundle install

          - name: Build Jekyll
            run: JEKYLL_ENV=production bundle exec jekyll build --destination gh-pages

          - run: ls -laR gh-pages
            name: List all this stuff 2
            
          - name: Publish
            uses: stefanzweifel/git-auto-commit-action@v4
            with:
                commit_message: 'Automatic build (orca.pet)'
                branch: gh-pages
                repository: gh-pages
