name: Website CI

on:
    push:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
            with:
                # Clone all history so timestamps are accurate
                fetch-depth: 0

          - name: Setup cache
            uses: actions/cache@v1
            with:
                path: vendor/bundle
                key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                restore-keys: |
                    ${{ runner.os }}-gems-

          - name: Set up dependencies
            run: sudo apt install brotli

          - name: Set up Ruby
            uses: ruby/setup-ruby@v1.32.1
            with:
                ruby-version: 2.5

          - name: Install Ruby dependencies
            run: |
                bundle config path vendor/bundle
                bundle install

          - name: Build Jekyll
            run: JEKYLL_ENV=production bundle exec jekyll build

          - name: Compressing
            run: find -type f \( -name "*.js" -o -name "*.txt" -o -name "*.xml" -o -name "*.html" -o -name "*.css" \) -exec brotli -Z {} \; -exec gzip -k9 {} \;

          - name: Publish
            uses: socram8888/ftp-hash-sync@master
            with:
                host: ftp.cluster021.hosting.ovh.net
                username: orcapetlmg
                password: ${{ secrets.FTP_PASSWORD }}
                source: _site
                destination: www
