# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push to master only.
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Build Jekyll website
    - name: Build Jekyll
      uses: jerryjvl/jekyll-build-action@v1

    # Publish it on my own server
    - name: Publish
      uses: socram8888/ftp-hash-sync@master
      with:
        host: ftp.cluster021.hosting.ovh.net
        username: orcapetlmg
        password: ${{ secrets.FTP_PASSWORD }}
        source: _site
        destination: www
